# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fd', 'Food'), ('dr', 'Drink'), ('cp', 'Cellphone'), ('lp', 'Laptop'), ('cl', 'Clothing'), ('el', 'Electronics'), ('hw', 'Homeware'), ('ft', 'Furniture'), ('bt', 'Beauty'), ('ot', 'Other')], default='other', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('mv', 'Movie'), ('tv', 'Television')], default='Movie', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_auction', models.ManyToManyField(related_name='in_media', to='auction.Auction')),
            ],
        ),
    ]
