# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('duration_seconds', models.IntegerField()),
                ('starting_bid', models.FloatField()),
                ('current_bid', models.FloatField()),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_auction_bids', to='auction.Auction')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_bids', to='login_reg.User')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('media_type', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_genre_medias', to='auction.Genre')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_medias', to='login_reg.User')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='fk_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_category_auctions', to='auction.Category'),
        ),
        migrations.AddField(
            model_name='auction',
            name='fk_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_media_auctions', to='auction.Media'),
        ),
        migrations.AddField(
            model_name='auction',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_auctions', to='login_reg.User'),
        ),
    ]
