# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='release_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
