# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20180528_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration_seconds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
