# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20180528_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='in_auction',
        ),
        migrations.AddField(
            model_name='media',
            name='in_auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='in_media', to='auction.Auction'),
            preserve_default=False,
        ),
    ]
