# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20180528_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='title',
            new_name='media_title',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='type',
            new_name='media_type',
        ),
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
