# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20180529_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='in_auction',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='fk_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_auction', to='auction.Media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='media_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='fk_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_auction', to='auction.Category'),
            preserve_default=False,
        ),
    ]
