# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20180529_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.SmallIntegerField(),
        ),
        migrations.AddField(
            model_name='bid',
            name='fk_auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_bid', to='auction.Auction'),
        ),
    ]
