# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20180529_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='fk_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_auction', to='auction.Category'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='fk_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_auction', to='auction.Media'),
        ),
    ]
